const imagePath = '../Assets/Images/';
const png = '.png';

const Images = {
  onboarding_0: require(imagePath + 'onboarding_0' + png),
  onboarding_1: require(imagePath + 'onboarding_1' + png),
  onboardingBackground: require(imagePath + 'onboardingBackground' + png),
  doubleTicks: require(imagePath + 'doubleTicks' + png),
  appIcon: require(imagePath + 'appIcon' + png),
  right: require(imagePath + 'right' + png),
  premium: require(imagePath + 'premium' + png),
  drawer_0: require(imagePath + 'drawer_0' + png),
  drawer_1: require(imagePath + 'drawer_1' + png),
  drawer_2: require(imagePath + 'drawer_2' + png),
  drawer_3: require(imagePath + 'drawer_3' + png),
  step_0: require(imagePath + 'step_0' + png),
  step_1: require(imagePath + 'step_1' + png),
  step_2: require(imagePath + 'step_2' + png),
  step_3: require(imagePath + 'step_3' + png),
  step_4: require(imagePath + 'step_4' + png),
  back: require(imagePath + 'back' + png),
  cross: require(imagePath + 'cross' + png),
  trueYellow: require(imagePath + 'trueYellow' + png),
  planSelected: require(imagePath + 'planSelected' + png),
  drawer: require(imagePath + 'drawer' + png),
  search: require(imagePath + 'search' + png),
  crown: require(imagePath + 'crown' + png),
  camera: require(imagePath + 'camera' + png),
  gallery: require(imagePath + 'gallery' + png),
  collageMaker: require(imagePath + 'collageMaker' + png),
  howToUse: require(imagePath + 'howToUse' + png),
  home_all: require(imagePath + 'home_all' + png),
  home_sketch: require(imagePath + 'home_sketch' + png),
  home_2d: require(imagePath + 'home_2d' + png),
  home_cartoon: require(imagePath + 'home_cartoon' + png),
  home_3d: require(imagePath + 'home_3d' + png),
  dummy: require(imagePath + 'dummy' + png),
};

export default Images;
