const Strings = {
  welcomeDescr:
    'Welcome To Toonme,\nWhere We Turn Your Photos\nInto Lively Cartoons!',
  Continue: 'Continue',
  Skip: 'Skip',
  Pro: 'Pro',
  HowToUse: 'How To Use',
  Camera: 'Camera',
  Gallery: 'Gallery',
  CollageMaker: 'Collage Maker',
  Free: 'Free',
  Edit: 'Edit',
  freeDesc: 'Try the FREE full\nPRO version',
  Tryforfree: 'Try for free',
  UpgradeNow: 'Upgrade Now !!!',
  UpgradeNowDesc: "You'll need a premium membership to connect",
  RemoveAllAds: 'Remove All Ads',
  UnlimitedDownload: 'Unlimited Download',
  Subscribe: 'Subscribe',
  SubscribeDesc: 'No commitments, Cancel Anytime',
  ToonmeCartoonsFromPhotos: 'Toonme - Cartoons From Photos',
  GetPremium: 'Get Premium',
  Save: 'Save',
  ToonMe: 'Toon Me',
  WelcomeToToonme: 'Welcome To Toonme',
  Wevalueyourprivacy: 'We value your privacy',
  Iagreetothe: 'I agree to the ',
  TermsofUse: 'Terms of Use',
  and: ' and ',
  acknowledgethatIhavereadthe: 'acknowledge that I have read the ',
  privacypolicy: 'privacy policy.',
  AcceptContinue: 'Accept & Continue',
  Next: 'Next',
  Home: 'Home',
  PrivacyPolicy: 'Privacy Policy',
  Ratings: 'Ratings',
  ShareThisApp: 'Share This App',
  step_0_title: 'Upload Your Photo',
  step_0_text:
    'Start by selecting a photo from your gallery or taking a new one.',
  step_1_title: 'Select a Cartoon Style',
  step_1_text:
    'Simply swipe through the styles & tap on your favorite to apply it to your photo.',
  step_2_title: 'Customize Your Cartoon',
  step_2_text: 'Make your cartoon unique with our customization options.',
  step_3_title: 'Add Fun Elements',
  step_3_text:
    'Drag and drop elements onto your cartoon & adjust their size and position to your liking.',
  step_4_title: 'Save and Share',
  step_4_text:
    "Once you're happy with your creation, save it your device or share it directly from the app.",
  MonthlyPlan: 'Monthly Plan',
  YearlyPlan: 'Yearly Plan',
  All: 'All',
  Sketch: 'Sketch',
  Cartoon: 'Cartoon',
  SelectCartoon: 'Select Cartoon',
  Result: 'Result',
  Preview: 'Preview',
  Edit: 'Edit',
  UnlockPremium: 'Unlock Premium',
  UnlockPremiumDesc:
    'Watch video to unlock for free and\nget your favorite cartoon',
  WatchVideo: 'Watch Video',
  HotFeature: 'Hot Feature',
  Male: 'Male',
  Female: 'Female',
  SelectGender: 'Select Gender',
  HotCartoons: 'Hot Cartoons',
  ContinueEditing: 'Continue Editing',
};

export default Strings;
